---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: brupop-controller
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: brupop-controller
  name: brupop-controller-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      brupop.bottlerocket.aws/component: brupop-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        brupop.bottlerocket.aws/component: brupop-controller
      namespace: {{ .Values.namespace }}
    spec:
      affinity:
        {{- with .Values.placement.controller.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.placement.controller.podAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      {{- with .Values.placement.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.placement.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - command:
            - "./controller"
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MAX_CONCURRENT_UPDATE
              value: "{{ .Values.max_concurrent_updates }}"
            - name: SCHEDULER_CRON_EXPRESSION
              value: "{{ .Values.scheduler_cron_expression}}"
            - name: LOGGING_FORMATTER
              value: "{{ .Values.logging.formatter }}"
            - name: LOGGING_ANSI_ENABLED
              value: "{{ .Values.logging.ansi_enabled }}"
            - name: TRACING_FILTER_DIRECTIVE
              value: "{{ .Values.logging.controller.tracing_filter }}"
          image: {{ .Values.image }}
          name: brupop
          resources:
            {{- toYaml .Values.resources.controller.resources | nindent 12 }}
      priorityClassName: {{ .Values.placement.controller.priorityClassName }}
      {{ if ((.Values.image_pull_secrets)) }}
      image_pull_secrets: 
        {{ .Values.image_pull_secrets }}
      {{ end }}
      serviceAccountName: brupop-controller-service-account
